/*
 * SDS_errorlist.h
 *
 *  Created on: 2016Äê12ÔÂ2ÈÕ
 *      Author: tupers
 */

#ifndef LIBINCLUDE_SDS_ERRORLIST_H_
#define LIBINCLUDE_SDS_ERRORLIST_H_

typedef enum SDS_ERROR_LIST
{
	ALG_SDS_OK=0,
	ALG_SDS_LIGHTONE=3,
	ALG_SDS_LIGHTTWO,
	ALG_SDS_OVERHEIGHT = 5,
	ALG_SDS_LIGHTZERO,
	ALG_SDS_LEFTBAD=9,
	ALG_SDS_CENTERBAD,
	ALG_SDS_RIGHTBAD,
	ALG_SDS_BADRELATIONSHIP,
	ALG_SDS_LIGHTOVERTHREE,
	ALG_SDS_LABELERROR=15,
	ALG_SDS_DEFAULTERROR=150,
	ALG_SDS_LABELLINGSTATE=255
};

#endif /* LIBINCLUDE_SDS_ERRORLIST_H_ */
