#ifndef ZCCAM_SERVER_MAIN_H
#define ZCCAM_SERVER_MAIN_H
#include <unistd.h>
#include <sys/socket.h>

#define EZ_SERVERPORT			7000
#define EZ_FRAMEPORT			8000

/***************** command table **************************/

/*************** STREAM  COMMAND *******************************/
enum _NET_MSG 
{
	/**System Page*/
	NET_MSG_LOGIN = 0,
	NET_MSG_GETUSER,
	NET_MSG_ADDUSER,
	NET_MSG_DELUSER,
	NET_MSG_GETSYSINFO,
	NET_MSG_SETSYSINFO,
	NET_MSG_UPDATE_DEFAULTPARAM,
	
	/**Network Page*/
	NET_MSG_SET_DHCP,
	NET_MSG_GET_DHCP,
	NET_MSG_SET_NETIP ,
	NET_MSG_GET_NETIP ,
	NET_MSG_SET_NETMASK ,
	NET_MSG_GET_NETMASK ,
	NET_MSG_SET_GTWAY ,
	NET_MSG_GET_GTWAY ,
	NET_MSG_NET_UPDATE,
	
	/**Camera Page */
	NET_MSG_SET_BRIGHTNESS ,
	NET_MSG_GET_BRIGHTNESS ,
	NET_MSG_SET_CONTRAST ,
	NET_MSG_GET_CONTRAST ,
	NET_MSG_SET_SATURATION ,
	NET_MSG_GET_SATURATION ,
	NET_MSG_SET_SHARPNESS ,
	NET_MSG_GET_SHARPNESS ,
	NET_MSG_SET_EXPOSURE,
	NET_MSG_GET_EXPOSURE,
	NET_MSG_SET_GAIN,
	NET_MSG_GET_GAIN,
	NET_MSG_SET_BLC ,
	NET_MSG_GET_BLC ,
	NET_MSG_SET_DYRANGE ,
	NET_MSG_GET_DYRANGE ,
	NET_MSG_SET_DYRANGESTRENGTH ,
	NET_MSG_GET_DYRANGESTRENGTH ,
	NET_MSG_SET_IMAGESOURCE ,
	NET_MSG_GET_IMAGESOURCE ,
	NET_MSG_SET_WB ,
	NET_MSG_GET_WB ,
	NET_MSG_SET_DAYNIGHTMODE,
	NET_MSG_GET_DAYNIGHTMODE,
	NET_MSG_SET_BINNING ,
	NET_MSG_GET_BINNING ,
	NET_MSG_SET_IMG2A ,
	NET_MSG_GET_IMG2A ,
	NET_MSG_SET_IMG2ATYPE ,
	NET_MSG_GET_IMG2ATYPE ,
	NET_MSG_SET_EXPRIORITY ,
	NET_MSG_GET_EXPRIORITY ,
	NET_MSG_SET_2A_PARAM ,
	NET_MSG_GET_2A_PARAM ,
	NET_MSG_SET_2A_WEIGHT,
	NET_MSG_GET_2A_WEIGHT,
	NET_MSG_SET_VIDSTAB ,
	NET_MSG_GET_VIDSTAB ,
	NET_MSG_SET_LDC ,
	NET_MSG_GET_LDC ,
	NET_MSG_SET_MIRROR,
	NET_MSG_GET_MIRROR,
	NET_MSG_SET_VNF, 
	NET_MSG_GET_VNF,
	NET_MSG_SET_VNF_MODE ,
	NET_MSG_GET_VNF_MODE ,
	NET_MSG_SET_VNFSTRENGTH ,
	NET_MSG_GET_VNFSTRENGTH ,
	NET_MSG_SET_FRAMECTR ,
	NET_MSG_GET_FRAMECTR,
    NET_MSG_RESET_PAYLOAD,
    NET_MSG_START_PAYLOAD,
    NET_MSG_PRINT_PAYLOAD,
    NET_MSG_GET_PAYLOAD,

	/*** LED ***/
#if 1
	NET_MSG_SET_LED,
	NET_MSG_GET_LED,
#endif	    
    /****IMG ALG*****/
    NET_MSG_GET_ALG_RESULT,
    NET_MSG_IMGALG_ENABLE,
    NET_MSG_IMGALG_DISABLE,
    NET_MSG_IMGALG_STATIC_IMG,
    NET_MSG_IMGALG_SENSOR_IMG,
	NET_MSG_IMGALG_SET_PARAM,
	NET_MSG_IMGALG_GET_PARAM,
	NET_MSG_IMGALG_DEF_PARAM,
	NET_MSG_IMGALG_NORMAL_MODE,
	NET_MSG_IMGALG_DEBUG_MODE,
	
    NET_MSG_GET_FRAME_IMG,
    NET_MSG_ENABLE_ENCODE,
    NET_MSG_DISABLE_ENCODE,
    NET_MSG_DEBUG_NONE,
    NET_MSG_DEBUG_SERIAL,
    NET_MSG_DEBUG_SOCKET,
    NET_MSG_DEBUG_QUIT,
    NET_MSG_RESET_SYSTEM
};

#define LOGNAME_MAXLENGTH       20
#define LOGPASSWD_MAXLENGTH     10

enum USER_ACCESS
{
    NORMAL_USER = 0,
    PROGRAM_USER
};


#define ACKCMD_SOK      0
#define ACKCMD_SFAIL    -1

#define NETMSG_MAXLEN	2048

#define FRAME_LEN		1400


typedef struct _NetMsg
{
    char cmd;
    int  ackCmd;
    int  cmdValueLen;
    char cmdValue[0];
}NetMsg;

typedef struct _ServerObj
{
	pthread_t tStreamThread;	//stream thread id
	pid_t pid;
	int	client_sd;
}ServerObj;

typedef struct
{
	unsigned port;
	char ip[20];
}DebugParam;

#endif
