/* ===========================================================================
* @path $(IPNCPATH)\include
*
* @desc
* .
* Copyright (c) Appro Photoelectron Inc.  2008
*
* Use of this software is controlled by the terms and conditions found
* in the license agreement under which this software has been supplied
*
* =========================================================================== */
/**
* @file sysctrl.h
* @brief Send commands to system server
*/
#ifndef __SYS_CONTROL_H__
#define __SYS_CONTROL_H__
/**
* @ingroup UTILITY API
* @defgroup SYSCTRL System command API

* This is the communication interface of system server.
* @{
*/
/* Date    2008/01/18 */
/* Version 1.00.01    */
/**
* @brief Command list.
*/
typedef enum
{
	/* Network Get Control */
  SFIELD_GET_DHCPC_ENABLE = 0x0000, ///< Get DHCP status.
  SFIELD_GET_HTTPPORT, ///< Get http port.
  SFIELD_GET_SNTP_FQDN, ///< Get SNTP FQDN.
  SFIELD_GET_TITLE, ///< Get IP netcam title.
  SFIELD_GET_MAC, ///< Get ethernet MAC address.
  SFIELD_GET_IP, ///< Get IP netcam IP address.
  SFIELD_GET_GATEWAY, ///< Get IP netcam gateway.
  SFIELD_GET_NETMASK, ///< Get IP netcam netmask.
  SFIELD_GET_FTP_SERVER_IP, ///< Get FTP FQDN.
  SFIELD_GET_FTP_USERNAME, ///< Get FTP user name.
  SFIELD_GET_FTP_PASSWORD, ///< Get FTP user password.
  SFIELD_GET_FTP_FOLDNAME, ///< Get FTP foleder.
  SFIELD_GET_FTP_IMAGEAMOUNT, ///< Get JPEG count at each FTP connection.
  SFIELD_GET_FTP_PID, ///< Get FTP process ID.
  SFIELD_GET_FTP_PORT, ///< Get FTP connection port.
  SFIELD_GET_SMTP_SERVER_IP, ///< Get SMTP FQDN.
  SFIELD_GET_SMTP_PORT, ///< Get SMTP PORT.
  SFIELD_GET_SMTP_AUTHENTICATION, ///< See if use authentication to send e-mail.
  SFIELD_GET_SMTP_USERNAME, ///< Get SMTP user name.
  SFIELD_GET_SMTP_PASSWORD, ///< Get SMTP password.
  SFIELD_GET_SMTP_SENDER_EMAIL_ADDRESS, ///< Get sender e-mail address.
  SFIELD_GET_SMTP_RECEIVER_EMAIL_ADDRESS, ///< Get receiver e-mail address.
  SFIELD_GET_SMTP_CC, ///< Get e-mail CC.
  SFIELD_GET_SMTP_SUBJECT, ///< Get e-mail subject.
  SFIELD_GET_SMTP_TEXT, ///< Get e-mail text.
  SFIELD_GET_SMTP_ATTACHMENTS, ///< Get e-mail JPEG attachments.
  SFIELD_GET_SMTP_VIEW, ///< Get e-mail style.
  SFIELD_GET_DNS, ///< Get DNS address.
  SFIELD_GET_DHCP_CONFIG, ///< Get DHCP status.
  SFIELD_GET_SD_FILE_NAME,///< Get current recording file name in SD card.
  //SFIELD_GET_UPNP_PORT,
  /* Network Set Control */
  SFIELD_SET_NETMASK      = 0x1000, ///< Set new netmask of IP netcam.
  SFIELD_SET_TIMEFORMAT, ///< Set display time format.
  SFIELD_SET_IP, ///< Set static IP address.
  SFIELD_SET_GATEWAY, ///< Set gateway in static IP mode.
  SFIELD_SET_DHCPC_ENABLE, ///< Set DHCP enable.
  SFIELD_SET_FTP_SERVER_IP, ///< Set FTP FQDN.
  SFIELD_SET_FTP_USERNAME, ///< Set FTP username.
  SFIELD_SET_FTP_PASSWORD, ///< Set FTP password.
  SFIELD_SET_FTP_FOLDNAME, ///< Set FTP folder.
  SFIELD_SET_FTP_IMAGEAMOUNT, ///< Set JPEG count at each FTP connection.
  SFIELD_SET_FTP_PID, ///< Save FTP process ID.
  SFIELD_SET_FTP_PORT, ///< Set FTP port.
  SFIELD_SET_SMTP_SERVER_IP, ///< Set SMTP FQDN.
  SFIELD_SET_SMTP_PORT, ///< Set SMTP PORT.
  SFIELD_SET_SMTP_AUTHENTICATION, ///< Let IP netcam use authentication to send e-mail or not.
  SFIELD_SET_SMTP_USERNAME, ///< Set SMTP user name.
  SFIELD_SET_SMTP_PASSWORD, ///< Set SMTP password.
  SFIELD_SET_SMTP_SENDER_EMAIL_ADDRESS, ///< Set sender e-mail address.
  SFIELD_SET_SMTP_RECEIVER_EMAIL_ADDRESS, ///< Set receiver e-mail address.
  SFIELD_SET_SMTP_CC, ///< Set e-mail CC.
  SFIELD_SET_SMTP_SUBJECT, ///< Set e-mail subject.
  SFIELD_SET_SMTP_TEXT, ///< Set e-mail text.
  SFIELD_SET_SMTP_ATTACHMENTS, ///< Set e-mail JPEG attachments.
  SFIELD_SET_SMTP_VIEW, ///< Set e-mail style.
  SFIELD_SET_DNS, ///< Set DNS address.
  SFIELD_SET_SNTP_SERVER, ///< Set SNTP FQDN.
  SFIELD_SET_DEMOCFG,
  SFIELD_SET_IMAGESOURCE, ///< Select NTSC/PAL mode.
  SFIELD_SET_SCHEDULE, ///< Set user define schedule.
  SFIELD_SET_SDAENABLE, ///< Enable save file to SD card when alarm happen or not.
  SFIELD_SET_AVIDURATION, ///< Set length of one AVI file(in seconds).
  SFIELD_SET_AVIFORMAT, ///< Set format of AVI file.
  SFIELD_SET_FTPFILEFORMAT, ///< Sent which kind of files to FTP.
  SFIELD_SET_SDFILEFORMAT, ///< Save which kind of files to SD card.
  SFIELD_SET_ATTFILEFORMAT, ///< Sent which kind of files to SMTP.
  SFIELD_SET_ASMTPATTACH,
  SFIELD_SET_FTP_RFTPENABLE, ///< Enable send file to FTP server at schedule.
  SFIELD_SET_SD_SDRENABLE, ///< Enable save file to SD card at schedule.
  SFIELD_SET_LOSTALARM, ///< Enable ethernet lost alarm or not.
  SFIELD_SET_ALARMDURATION, ///< Set how long will one alarm last.
  SFIELD_SET_AFTPENABLE, ///< Enable send file to FTP server when alarm happen or not.
  SFIELD_SET_ASMTPENABLE, ///< Enable send file to SMTP server when alarm happen or not.
  SFIELD_SET_IMAGEDEFAULT,///< Set all image setting to default.
  /* Live video Page */
  SFIELD_SET_CLICK_SNAP_FILENAME,
  SFIELD_SET_CLICK_SNAP_STORAGE,

  /* Video Image Page */
    SFIELD_SET_TITLE, ///< Set IP netcam title.
  	SFIELD_SET_VIDEO_MODE,
  	SFIELD_SET_VIDEOCODECCOMBO,
  	SFIELD_SET_VIDEOCODECRES, ///< Set video resolution. This operation will take several time.
  	SFIELD_SET_MPEG41_BITRATE, ///< Set MPEG1 bitrate.
  	SFIELD_SET_MPEG42_BITRATE,///< Set MPEG2 bitrate.
  	SFIELD_SET_JQUALITY, ///< Set JPEG encode quality.
  	SFIELD_SET_FRAMERATE1, ///< Set MPEG1 frame rate.
  	SFIELD_SET_FRAMERATE2, ///< Set MPEG2 frame rate.
    SFIELD_SET_FRAMERATE3, ///< Set JPEG frame rate.
	SFIELD_SET_RATE_CONTROL1,
    SFIELD_SET_RATE_CONTROL2,
    SFIELD_SET_DSTAMPENABLE1,
    SFIELD_SET_DSTAMPENABLE2,
    SFIELD_SET_DSTAMPENABLE3,
    SFIELD_SET_TSTAMPENABLE1,
    SFIELD_SET_TSTAMPENABLE2,
    SFIELD_SET_TSTAMPENABLE3,
    SFIELD_SET_LOGOENABLE1,
    SFIELD_SET_LOGOENABLE2,
    SFIELD_SET_LOGOENABLE3,
    SFIELD_SET_LOGO_POSITION1,
    SFIELD_SET_LOGO_POSITION2,
    SFIELD_SET_LOGO_POSITION3,
    SFIELD_SET_TEXTENABLE1,
    SFIELD_SET_TEXTENABLE2,
    SFIELD_SET_TEXTENABLE3,
    SFIELD_SET_TEXT_POSITION1,
    SFIELD_SET_TEXT_POSITION2,
    SFIELD_SET_TEXT_POSITION3,
    SFIELD_SET_OVERLAY_TEXT1,
    SFIELD_SET_OVERLAY_TEXT2,
    SFIELD_SET_OVERLAY_TEXT3,
    SFIELD_SET_DETAIL_INFO1,
    SFIELD_SET_DETAIL_INFO2,
    SFIELD_SET_DETAIL_INFO3,
    SFIELD_SET_ENCRYPTION,
    SFIELD_SET_LOCAL_DISPLAY,
     SFIELD_SET_MIRROR,
	 /* Video Advanced Page */
    SFIELD_SET_IPRATIO1,
    SFIELD_SET_IPRATIO2,
    SFIELD_SET_IPRATIO3,
    SFIELD_SET_FORCE_IFRAME1,
    SFIELD_SET_FORCE_IFRAME2,
    SFIELD_SET_FORCE_IFRAME3,
    SFIELD_SET_QPINIT1,
    SFIELD_SET_QPINIT2,
    SFIELD_SET_QPINIT3,
    SFIELD_SET_QPMIN1,
    SFIELD_SET_QPMIN2,
    SFIELD_SET_QPMIN3,
    SFIELD_SET_QPMAX1,
    SFIELD_SET_QPMAX2,
    SFIELD_SET_QPMAX3,
    SFIELD_SET_MECONFIG1,
    SFIELD_SET_MECONFIG2,
    SFIELD_SET_MECONFIG3,
    SFIELD_SET_PACKETSIZE1,
    SFIELD_SET_PACKETSIZE2,
    SFIELD_SET_PACKETSIZE3,
    SFIELD_SET_ROI_ENABLE1,
    SFIELD_SET_ROI_ENABLE2,
    SFIELD_SET_ROI_ENABLE3,
    SFIELD_SET_STR1X1,
    SFIELD_SET_STR1Y1,
    SFIELD_SET_STR1W1,
    SFIELD_SET_STR1H1,
    SFIELD_SET_STR1X2,
    SFIELD_SET_STR1Y2,
    SFIELD_SET_STR1W2,
    SFIELD_SET_STR1H2,
    SFIELD_SET_STR1X3,
    SFIELD_SET_STR1Y3,
    SFIELD_SET_STR1W3,
    SFIELD_SET_STR1H3,
    SFIELD_SET_STR2X1,
    SFIELD_SET_STR2Y1,
    SFIELD_SET_STR2W1,
    SFIELD_SET_STR2H1,
    SFIELD_SET_STR2X2,
    SFIELD_SET_STR2Y2,
    SFIELD_SET_STR2W2,
    SFIELD_SET_STR2H2,
    SFIELD_SET_STR2X3,
    SFIELD_SET_STR2Y3,
    SFIELD_SET_STR2W3,
    SFIELD_SET_STR2H3,
    SFIELD_SET_STR3X1,
    SFIELD_SET_STR3Y1,
    SFIELD_SET_STR3W1,
    SFIELD_SET_STR3H1,
    SFIELD_SET_STR3X2,
    SFIELD_SET_STR3Y2,
    SFIELD_SET_STR3W2,
    SFIELD_SET_STR3H2,
    SFIELD_SET_STR3X3,
    SFIELD_SET_STR3Y3,
    SFIELD_SET_STR3W3,
    SFIELD_SET_STR3H3,

  /* Video Analytics */
  SFIELD_SET_MOTIONENABLE, ///< Enable motion detection or not.
  SFIELD_SET_MOTIONCENABLE, ///< Use customer define or normal mode.
  SFIELD_SET_MOTIONLEVEL, ///< Set motion level in normal mode.
  SFIELD_SET_MOTIONCVALUE, ///< Set customer value at customer mode.
  SFIELD_SET_MOTIONBLOCK, ///< Define motion blocks.
  SFIELD_SET_FDETECT,
  SFIELD_SET_FDX,
  SFIELD_SET_FDY,
  SFIELD_SET_FDW,
  SFIELD_SET_FDH,
  SFIELD_SET_FDCONF_LEVEL,
  SFIELD_SET_FD_DIRECTION,
  SFIELD_SET_FRECOGNITION,
  SFIELD_SET_FRCONF_LEVEL,
  SFIELD_SET_FR_DATABASE,
  SFIELD_SET_PRIVACY_MASK,
  SFIELD_SET_MASK_OPTIONS,
  /* Camera Page */
  SFIELD_SET_BRIGHTNESS, ///< Set brightness.
  SFIELD_SET_CONTRAST, ///< Set contrast.
  SFIELD_SET_SATURATION, ///< Set saturation.
  SFIELD_SET_SHARPNESS, ///< Set sharpness.
  SFIELD_SET_BLC,
  SFIELD_SET_DYNRANGE,
  SFIELD_SET_DYNRANGESTRENGTH,
  SFIELD_SET_BACKLIGHT, ///< Set backlight mode of IP netcam.
  SFIELD_SET_WHITE_BALANCE, ///< Set whitebalance moe of IP netcam.
  SFIELD_SET_DAY_NIGHT, ///< Set day/night mode of IP netcam.
  SFIELD_SET_HISTOGRAM,
  SFIELD_SET_BINNING, ///< Set binning mode.
  SFIELD_SET_IMAGE2A,
  SFIELD_SET_IMAGE2ATYPE,
  SFIELD_SET_EXPPRIORITY,
  SFIELD_SET_VSTAB,
  SFIELD_SET_LDC,
  SFIELD_SET_VNF,
  SFIELD_SET_VNFMODE,
  SFIELD_SET_VNFSTRENGTH,
  SFIELD_SET_IMAGING,  ///< imaging settings>
  SFIELD_SET_FRAMECTRL,
  SFIELD_SET_AUTOIRIS_VOL,
  /* Audio Page */
  SFIELD_SET_AUDIOENABLE, ///< Enable audio send to web site or not.
  SFIELD_SET_AUDIOMODE,
  SFIELD_SET_AUDIOINVOLUME, ///< Set alarm audio volume
  SFIELD_SET_AUDIO_ENCODE,
  SFIELD_SET_AUDIO_SOURCE,   ///< add audio source in media profile>
  SFIELD_SET_AUDIO_SAMPLERATE,
  SFIELD_SET_AUDIO_BITRATE,
  SFIELD_SET_AUDIO_ALARMLEVEL,
  SFIELD_SET_AUDIOOUTVOLUME,
  SFIELD_SET_AUDIORECEIVERENABLE,
  SFIELD_SET_AUDIOSERVERIP,
  /* Date time Page */
  SFIELD_SET_DAYLIGHT, ///< Set system time to use daylight or not.
  SFIELD_SET_TIMEZONE, ///< Set system time zone.
  SFIELD_SET_DATEFORMAT,
  SFIELD_SET_TSTAMPFORMAT, ///< Set timestamp format.
  SFIELD_SET_DATEPPOS,
  SFIELD_SET_TIMEPOS,
  /* Network & Port Page */
  SFIELD_SET_MULTICAST, ///< Set Multicast.
  SFIELD_SET_HTTPPORT, ///< set web site port. This operation may take serveral time.
  SFIELD_SET_HTTPSPORT,
  SFIELD_SET_GIOINTYPE, ///< Set GIO input alarm triger type(high triger or low triger).
  SFIELD_SET_GIOOUTTYPE, ///< Set GIO output high or low.
  SFIELD_SET_RS485,
  /* Alarm & Storage */
  SFIELD_SET_ALARM_ENABLE,
  SFIELD_SET_EXT_ALARM,
  SFIELD_SET_AUDIOALARM,
  SFIELD_SET_ALARM_AUDIOPLAY,
  SFIELD_SET_ALARM_AUDIOFILE,
  SFIELD_SET_ALARMLOCAL,
  SFIELD_SET_RECORDLOCAL,
  SFIELD_SET_SCHEDULE_REPEAT_ENABLE,
  SFIELD_SET_SCHEDULE_NUMWEEKS,
  SFIELD_SET_SCHEDULE_INFINITE_ENABLE,
  /* Other Contorl */
  SFIELD_DEL_SCHEDULE = 0x2000, ///< Delete all exist schedule.
  SFIELD_DO_LOGIN, ///< Do user login.
  SFIELD_GET_USER_AUTHORITY, ///< Get user authority by name.
  SFIELD_ADD_USER, ///< Add/change user acount.
  SFIELD_DEL_USER, ///< Delete user acount.
  SFIELD_IPNCPTZ, ///< Contorl PTZ.
  SFIELD_INIT_IPNCPTZ, ///< PTZ init 4X.
  SFIELD_SD_FORMAT, ///< Format SD card.
  SFIELD_SD_UNMOUNT, ///< Unmount SD card.
  SFIELD_SCHEDULE_STOP, ///< Stop schedule.
  SFIELD_SCHEDULE_RESUME, ///< Resume schedule.
  /* Maintainence */
  SFIELD_SET_DEFAULT,
  SFIELD_SET_CLEARSYSLOG,
  SFIELD_SET_CLEARACCESSLOG,
//gio
  SFIELD_SET_GIOINENABLE, ///< Enable GIO input alarm or not.
  SFIELD_SET_GIOOUTENABLE, ///< Enable GIO ouput at alarm or not.
  SFIELD_SET_TSTAMPENABLE, ///< Enable timestamp or not.
  SFIELD_ADD_PROFILE,         //<create new media profile
  SFIELD_ADD_VIDEOSOURCE_CONF,       //<add video source configuration>
  SFIELD_ADD_AUDIOSOURCE_CONF,
  SFIELD_SET_AUDIOSOURCE_CONF,
  SFIELD_ADD_AUDIOENCODER_CONF,
  SFIELD_SET_AUDIOENCODER_CONF,
  SFIELD_SET_VIDEOSOURCE_CONF,
  SFIELD_ADD_VIDEOENCODER_CONF,
  SFIELD_SET_VIDEOENCODER_CONF,
  SFIELD_DEL_VIDEOENCODER_CONF,
  SFIELD_ADD_AUDIO_SOURCE,
  SFIELD_DEL_AUDIO_SOURCE,
  SFIELD_DEL_PROFILE,
  SFIELD_DIS_MODE,               //discovery mode
  SFIELD_ADD_SCOPE,              //Add Scopes <onvif>
  SFIELD_DEL_SCOPE,		 //Delete Scopes
  SFIELD_SET_SCOPE,  //Set SCopes
  SFIELD_SET_VIDEOANALYTICS_CONF,       //set video analytics
  SFIELD_SET_VIDEOOUTPUT_CONF,       //set video output
  SFIELD_SET_RELAYS_CONF,             //set relays
  SFIELD_SET_RELAY_LOGICALSTATE,
  SFIELD_SET_HOSTNAME,
  SFIELD_SET_METADATA,
  SFIELD_ADD_METADATA,
  SFIELD_DEL_METADATA,
  SFIELD_DEL_AUDIO_ENCODER,

  /* DMVA Specific */
  SFIELD_SET_DMVAENABLE,
  SFIELD_SET_DMVAALGOFRAMERATE,
  SFIELD_SET_DMVAALGODETECTFREQ,
  SFIELD_SET_DMVAEVTRECORDENABLE,
  SFIELD_SET_DMVASMETATRACKERENABLE,
  /* DMVA TZ PAGE */
  SFIELD_SET_DMVA_TZ_SENSITIVITY,
  SFIELD_SET_DMVA_TZ_PERSONMINWIDTH,
  SFIELD_SET_DMVA_TZ_PERSONMINHEIGHT,
  SFIELD_SET_DMVA_TZ_VEHICLEMINWIDTH,
  SFIELD_SET_DMVA_TZ_VEHICLEMINHEIGHT,
  SFIELD_SET_DMVA_TZ_PERSONMAXWIDTH,
  SFIELD_SET_DMVA_TZ_PERSONMAXHEIGHT,
  SFIELD_SET_DMVA_TZ_VEHICLEMAXWIDTH,
  SFIELD_SET_DMVA_TZ_VEHICLEMAXHEIGHT,
  SFIELD_SET_DMVA_TZ_DIRECTION,
  SFIELD_SET_DMVA_TZ_PRESENTADJUST,
  SFIELD_SET_DMVA_TZ_ENABLE,

  SFIELD_SET_DMVA_TZ_ZONE1_ROI_NUMSIDES,
  SFIELD_SET_DMVA_TZ_ZONE2_ROI_NUMSIDES,

  SFIELD_SET_DMVA_TZ_ZONE1_X01,
  SFIELD_SET_DMVA_TZ_ZONE1_X02,
  SFIELD_SET_DMVA_TZ_ZONE1_X03,
  SFIELD_SET_DMVA_TZ_ZONE1_X04,
  SFIELD_SET_DMVA_TZ_ZONE1_X05,
  SFIELD_SET_DMVA_TZ_ZONE1_X06,
  SFIELD_SET_DMVA_TZ_ZONE1_X07,
  SFIELD_SET_DMVA_TZ_ZONE1_X08,
  SFIELD_SET_DMVA_TZ_ZONE1_X09,
  SFIELD_SET_DMVA_TZ_ZONE1_X10,
  SFIELD_SET_DMVA_TZ_ZONE1_X11,
  SFIELD_SET_DMVA_TZ_ZONE1_X12,
  SFIELD_SET_DMVA_TZ_ZONE1_X13,
  SFIELD_SET_DMVA_TZ_ZONE1_X14,
  SFIELD_SET_DMVA_TZ_ZONE1_X15,
  SFIELD_SET_DMVA_TZ_ZONE1_X16,

  SFIELD_SET_DMVA_TZ_ZONE1_Y01,
  SFIELD_SET_DMVA_TZ_ZONE1_Y02,
  SFIELD_SET_DMVA_TZ_ZONE1_Y03,
  SFIELD_SET_DMVA_TZ_ZONE1_Y04,
  SFIELD_SET_DMVA_TZ_ZONE1_Y05,
  SFIELD_SET_DMVA_TZ_ZONE1_Y06,
  SFIELD_SET_DMVA_TZ_ZONE1_Y07,
  SFIELD_SET_DMVA_TZ_ZONE1_Y08,
  SFIELD_SET_DMVA_TZ_ZONE1_Y09,
  SFIELD_SET_DMVA_TZ_ZONE1_Y10,
  SFIELD_SET_DMVA_TZ_ZONE1_Y11,
  SFIELD_SET_DMVA_TZ_ZONE1_Y12,
  SFIELD_SET_DMVA_TZ_ZONE1_Y13,
  SFIELD_SET_DMVA_TZ_ZONE1_Y14,
  SFIELD_SET_DMVA_TZ_ZONE1_Y15,
  SFIELD_SET_DMVA_TZ_ZONE1_Y16,

  SFIELD_SET_DMVA_TZ_ZONE2_X01,
  SFIELD_SET_DMVA_TZ_ZONE2_X02,
  SFIELD_SET_DMVA_TZ_ZONE2_X03,
  SFIELD_SET_DMVA_TZ_ZONE2_X04,
  SFIELD_SET_DMVA_TZ_ZONE2_X05,
  SFIELD_SET_DMVA_TZ_ZONE2_X06,
  SFIELD_SET_DMVA_TZ_ZONE2_X07,
  SFIELD_SET_DMVA_TZ_ZONE2_X08,
  SFIELD_SET_DMVA_TZ_ZONE2_X09,
  SFIELD_SET_DMVA_TZ_ZONE2_X10,
  SFIELD_SET_DMVA_TZ_ZONE2_X11,
  SFIELD_SET_DMVA_TZ_ZONE2_X12,
  SFIELD_SET_DMVA_TZ_ZONE2_X13,
  SFIELD_SET_DMVA_TZ_ZONE2_X14,
  SFIELD_SET_DMVA_TZ_ZONE2_X15,
  SFIELD_SET_DMVA_TZ_ZONE2_X16,

  SFIELD_SET_DMVA_TZ_ZONE2_Y01,
  SFIELD_SET_DMVA_TZ_ZONE2_Y02,
  SFIELD_SET_DMVA_TZ_ZONE2_Y03,
  SFIELD_SET_DMVA_TZ_ZONE2_Y04,
  SFIELD_SET_DMVA_TZ_ZONE2_Y05,
  SFIELD_SET_DMVA_TZ_ZONE2_Y06,
  SFIELD_SET_DMVA_TZ_ZONE2_Y07,
  SFIELD_SET_DMVA_TZ_ZONE2_Y08,
  SFIELD_SET_DMVA_TZ_ZONE2_Y09,
  SFIELD_SET_DMVA_TZ_ZONE2_Y10,
  SFIELD_SET_DMVA_TZ_ZONE2_Y11,
  SFIELD_SET_DMVA_TZ_ZONE2_Y12,
  SFIELD_SET_DMVA_TZ_ZONE2_Y13,
  SFIELD_SET_DMVA_TZ_ZONE2_Y14,
  SFIELD_SET_DMVA_TZ_ZONE2_Y15,
  SFIELD_SET_DMVA_TZ_ZONE2_Y16,
  SFIELD_SET_DMVA_TZ_SAVE,
  SFIELD_SET_DMVA_TZ_LOAD,

  /* DMVA MAIN ANALYTICS PAGE */
  SFIELD_SET_DMVA_MAIN_CAMID,
  SFIELD_SET_DMVA_MAIN_GETSCHEDULE,
  SFIELD_SET_DMVA_MAIN_FD,
  SFIELD_SET_DMVA_MAIN_CTDIMDSMETATZOC,
  SFIELD_SET_DMVA_MAIN_DISPLAYOPTIONS,
  SFIELD_SET_DMVA_MAIN_RECORDINGVAME,
  SFIELD_SET_DMVA_MAIN_ACTIONPLAYSENDSEARCHTRASH,
  SFIELD_SET_DMVA_MAIN_SELECTEVENT,
  SFIELD_SET_DMVA_MAIN_ARCHIVEFLAG,
  SFIELD_SET_DMVA_MAIN_EVENTTYPE,

  SFIELD_SET_DMVA_MAIN_EL_START_MONTH,
  SFIELD_SET_DMVA_MAIN_EL_START_DAY,
  SFIELD_SET_DMVA_MAIN_EL_START_TIME,
  SFIELD_SET_DMVA_MAIN_EL_END_MONTH,
  SFIELD_SET_DMVA_MAIN_EL_END_DAY,
  SFIELD_SET_DMVA_MAIN_EL_END_TIME,

  SFIELD_SET_DMVA_MAIN_EL_TIME_STAMP_LABEL,
  SFIELD_SET_DMVA_MAIN_EL_EVENT_DETAILS_LABEL,

  /* DMVA ADVANCED SETTINGS  PAGE */
  SFIELD_SET_DMVA_ADVANCED_OBJECTMETADATA,
  SFIELD_SET_DMVA_ADVANCED_OVLPROPFONTTYPE,
  SFIELD_SET_DMVA_ADVANCED_OVLPROPFONTSIZE,
  SFIELD_SET_DMVA_ADVANCED_OVLPROPFONTCOLOR,
  SFIELD_SET_DMVA_ADVANCED_OVLPROPBOXCOLOR,
  SFIELD_SET_DMVA_ADVANCED_OVLPROPCENTROIDCOLOR,
  SFIELD_SET_DMVA_ADVANCED_OVLPROPACTIVEZONECOLOR,
  SFIELD_SET_DMVA_ADVANCED_OVLPROPINACTIVEZONECOLOR,
  SFIELD_SET_DMVA_ADVANCED_OVLPROPVELOCITYCOLOR,
  SFIELD_SET_DMVA_ADVANCED_ENVPROFILELOAD,
  SFIELD_SET_DMVA_ADVANCED_ENVPROFILESTORE,
  SFIELD_SET_DMVA_ADVANCED_ENVPROFILECLEAR,
  SFIELD_SET_DMVA_ADVANCED_ENVPROFILESTATE,
  SFIELD_SET_DMVA_ADVANCED_ENVPROFILEDESC,

  /* DMVA event delete */
  SFIELD_SET_DMVA_EVENT_DELETE_INDEX,
  SFIELD_SET_DMVA_EVENT_DELETE_START_INDEX,
  SFIELD_SET_DMVA_EVENT_DELETE_END_INDEX,
  SFIELD_SET_DMVA_EVENT_DELETE_ALL,

  /* DMVA CTD PAGE */
  SFIELD_SET_DMVA_CTD_ENV1,
  SFIELD_SET_DMVA_CTD_ENV2,
  SFIELD_SET_DMVA_CTD_SENSITIVITY,
  SFIELD_SET_DMVA_CTD_RESETTIME,

  /* DMVA OC PAGE */
  SFIELD_SET_DMVA_OC_SENSITIVITY,
  SFIELD_SET_DMVA_OC_OBJECTWIDTH,
  SFIELD_SET_DMVA_OC_OBJECTHEIGHT,
  SFIELD_SET_DMVA_OC_DIRECTION,
  SFIELD_SET_DMVA_OC_ENABLE,
  SFIELD_SET_DMVA_OC_LEFTRIGHT,
  SFIELD_SET_DMVA_OC_TOPBOTTOM,
  SFIELD_SET_DMVA_OC_SAVE,
  SFIELD_SET_DMVA_OC_LOAD,

  /* DMVA SMETA PAGE */
  SFIELD_SET_DMVA_SMETA_SENSITIVITY,
  SFIELD_SET_DMVA_SMETA_ENABLESTREAMINGDATA,
  SFIELD_SET_DMVA_SMETA_STREAMBB,
  SFIELD_SET_DMVA_SMETA_STREAMVELOCITY,
  SFIELD_SET_DMVA_SMETA_STREAMHISTOGRAM,
  SFIELD_SET_DMVA_SMETA_STREAMMOMENTS,
  SFIELD_SET_DMVA_SMETA_PRESENTADJUST,
  SFIELD_SET_DMVA_SMETA_PERSONMINWIDTH,
  SFIELD_SET_DMVA_SMETA_PERSONMINHEIGHT,
  SFIELD_SET_DMVA_SMETA_VEHICLEMINWIDTH,
  SFIELD_SET_DMVA_SMETA_VEHICLEMINHEIGHT,
  SFIELD_SET_DMVA_SMETA_PERSONMAXWIDTH,
  SFIELD_SET_DMVA_SMETA_PERSONMAXHEIGHT,
  SFIELD_SET_DMVA_SMETA_VEHICLEMAXWIDTH,
  SFIELD_SET_DMVA_SMETA_VEHICLEMAXHEIGHT,
  SFIELD_SET_DMVA_SMETA_NUMZONES,
  SFIELD_SET_DMVA_SMETA_ZONE1_ROI_NUMSIDES,
  SFIELD_SET_DMVA_SMETA_ZONE1_X01,
  SFIELD_SET_DMVA_SMETA_ZONE1_X02,
  SFIELD_SET_DMVA_SMETA_ZONE1_X03,
  SFIELD_SET_DMVA_SMETA_ZONE1_X04,
  SFIELD_SET_DMVA_SMETA_ZONE1_X05,
  SFIELD_SET_DMVA_SMETA_ZONE1_X06,
  SFIELD_SET_DMVA_SMETA_ZONE1_X07,
  SFIELD_SET_DMVA_SMETA_ZONE1_X08,
  SFIELD_SET_DMVA_SMETA_ZONE1_X09,
  SFIELD_SET_DMVA_SMETA_ZONE1_X10,
  SFIELD_SET_DMVA_SMETA_ZONE1_X11,
  SFIELD_SET_DMVA_SMETA_ZONE1_X12,
  SFIELD_SET_DMVA_SMETA_ZONE1_X13,
  SFIELD_SET_DMVA_SMETA_ZONE1_X14,
  SFIELD_SET_DMVA_SMETA_ZONE1_X15,
  SFIELD_SET_DMVA_SMETA_ZONE1_X16,

  SFIELD_SET_DMVA_SMETA_ZONE1_Y01,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y02,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y03,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y04,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y05,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y06,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y07,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y08,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y09,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y10,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y11,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y12,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y13,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y14,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y15,
  SFIELD_SET_DMVA_SMETA_ZONE1_Y16,
  SFIELD_SET_DMVA_SMETA_ZONE1_LABEL,
  SFIELD_SET_DMVA_SMETA_SAVE,
  SFIELD_SET_DMVA_SMETA_LOAD,

  /* DMVA IMD PAGE */
  SFIELD_SET_DMVA_IMD_SENSITIVITY,
  SFIELD_SET_DMVA_IMD_PRESENTADJUST,
  SFIELD_SET_DMVA_IMD_PERSONMINWIDTH,
  SFIELD_SET_DMVA_IMD_PERSONMINHEIGHT,
  SFIELD_SET_DMVA_IMD_VEHICLEMINWIDTH,
  SFIELD_SET_DMVA_IMD_VEHICLEMINHEIGHT,
  SFIELD_SET_DMVA_IMD_PERSONMAXWIDTH,
  SFIELD_SET_DMVA_IMD_PERSONMAXHEIGHT,
  SFIELD_SET_DMVA_IMD_VEHICLEMAXWIDTH,
  SFIELD_SET_DMVA_IMD_VEHICLEMAXHEIGHT,
  SFIELD_SET_DMVA_IMD_NUMZONES,
  SFIELD_SET_DMVA_IMD_ZONEENABLE,

  SFIELD_SET_DMVA_IMD_ZONE1_ROI_NUMSIDES,
  SFIELD_SET_DMVA_IMD_ZONE2_ROI_NUMSIDES,
  SFIELD_SET_DMVA_IMD_ZONE3_ROI_NUMSIDES,
  SFIELD_SET_DMVA_IMD_ZONE4_ROI_NUMSIDES,

  SFIELD_SET_DMVA_IMD_ZONE1_X01,
  SFIELD_SET_DMVA_IMD_ZONE1_X02,
  SFIELD_SET_DMVA_IMD_ZONE1_X03,
  SFIELD_SET_DMVA_IMD_ZONE1_X04,
  SFIELD_SET_DMVA_IMD_ZONE1_X05,
  SFIELD_SET_DMVA_IMD_ZONE1_X06,
  SFIELD_SET_DMVA_IMD_ZONE1_X07,
  SFIELD_SET_DMVA_IMD_ZONE1_X08,
  SFIELD_SET_DMVA_IMD_ZONE1_X09,
  SFIELD_SET_DMVA_IMD_ZONE1_X10,
  SFIELD_SET_DMVA_IMD_ZONE1_X11,
  SFIELD_SET_DMVA_IMD_ZONE1_X12,
  SFIELD_SET_DMVA_IMD_ZONE1_X13,
  SFIELD_SET_DMVA_IMD_ZONE1_X14,
  SFIELD_SET_DMVA_IMD_ZONE1_X15,
  SFIELD_SET_DMVA_IMD_ZONE1_X16,

  SFIELD_SET_DMVA_IMD_ZONE1_Y01,
  SFIELD_SET_DMVA_IMD_ZONE1_Y02,
  SFIELD_SET_DMVA_IMD_ZONE1_Y03,
  SFIELD_SET_DMVA_IMD_ZONE1_Y04,
  SFIELD_SET_DMVA_IMD_ZONE1_Y05,
  SFIELD_SET_DMVA_IMD_ZONE1_Y06,
  SFIELD_SET_DMVA_IMD_ZONE1_Y07,
  SFIELD_SET_DMVA_IMD_ZONE1_Y08,
  SFIELD_SET_DMVA_IMD_ZONE1_Y09,
  SFIELD_SET_DMVA_IMD_ZONE1_Y10,
  SFIELD_SET_DMVA_IMD_ZONE1_Y11,
  SFIELD_SET_DMVA_IMD_ZONE1_Y12,
  SFIELD_SET_DMVA_IMD_ZONE1_Y13,
  SFIELD_SET_DMVA_IMD_ZONE1_Y14,
  SFIELD_SET_DMVA_IMD_ZONE1_Y15,
  SFIELD_SET_DMVA_IMD_ZONE1_Y16,

  SFIELD_SET_DMVA_IMD_ZONE2_X01,
  SFIELD_SET_DMVA_IMD_ZONE2_X02,
  SFIELD_SET_DMVA_IMD_ZONE2_X03,
  SFIELD_SET_DMVA_IMD_ZONE2_X04,
  SFIELD_SET_DMVA_IMD_ZONE2_X05,
  SFIELD_SET_DMVA_IMD_ZONE2_X06,
  SFIELD_SET_DMVA_IMD_ZONE2_X07,
  SFIELD_SET_DMVA_IMD_ZONE2_X08,
  SFIELD_SET_DMVA_IMD_ZONE2_X09,
  SFIELD_SET_DMVA_IMD_ZONE2_X10,
  SFIELD_SET_DMVA_IMD_ZONE2_X11,
  SFIELD_SET_DMVA_IMD_ZONE2_X12,
  SFIELD_SET_DMVA_IMD_ZONE2_X13,
  SFIELD_SET_DMVA_IMD_ZONE2_X14,
  SFIELD_SET_DMVA_IMD_ZONE2_X15,
  SFIELD_SET_DMVA_IMD_ZONE2_X16,

  SFIELD_SET_DMVA_IMD_ZONE2_Y01,
  SFIELD_SET_DMVA_IMD_ZONE2_Y02,
  SFIELD_SET_DMVA_IMD_ZONE2_Y03,
  SFIELD_SET_DMVA_IMD_ZONE2_Y04,
  SFIELD_SET_DMVA_IMD_ZONE2_Y05,
  SFIELD_SET_DMVA_IMD_ZONE2_Y06,
  SFIELD_SET_DMVA_IMD_ZONE2_Y07,
  SFIELD_SET_DMVA_IMD_ZONE2_Y08,
  SFIELD_SET_DMVA_IMD_ZONE2_Y09,
  SFIELD_SET_DMVA_IMD_ZONE2_Y10,
  SFIELD_SET_DMVA_IMD_ZONE2_Y11,
  SFIELD_SET_DMVA_IMD_ZONE2_Y12,
  SFIELD_SET_DMVA_IMD_ZONE2_Y13,
  SFIELD_SET_DMVA_IMD_ZONE2_Y14,
  SFIELD_SET_DMVA_IMD_ZONE2_Y15,
  SFIELD_SET_DMVA_IMD_ZONE2_Y16,

  SFIELD_SET_DMVA_IMD_ZONE3_X01,
  SFIELD_SET_DMVA_IMD_ZONE3_X02,
  SFIELD_SET_DMVA_IMD_ZONE3_X03,
  SFIELD_SET_DMVA_IMD_ZONE3_X04,
  SFIELD_SET_DMVA_IMD_ZONE3_X05,
  SFIELD_SET_DMVA_IMD_ZONE3_X06,
  SFIELD_SET_DMVA_IMD_ZONE3_X07,
  SFIELD_SET_DMVA_IMD_ZONE3_X08,
  SFIELD_SET_DMVA_IMD_ZONE3_X09,
  SFIELD_SET_DMVA_IMD_ZONE3_X10,
  SFIELD_SET_DMVA_IMD_ZONE3_X11,
  SFIELD_SET_DMVA_IMD_ZONE3_X12,
  SFIELD_SET_DMVA_IMD_ZONE3_X13,
  SFIELD_SET_DMVA_IMD_ZONE3_X14,
  SFIELD_SET_DMVA_IMD_ZONE3_X15,
  SFIELD_SET_DMVA_IMD_ZONE3_X16,

  SFIELD_SET_DMVA_IMD_ZONE3_Y01,
  SFIELD_SET_DMVA_IMD_ZONE3_Y02,
  SFIELD_SET_DMVA_IMD_ZONE3_Y03,
  SFIELD_SET_DMVA_IMD_ZONE3_Y04,
  SFIELD_SET_DMVA_IMD_ZONE3_Y05,
  SFIELD_SET_DMVA_IMD_ZONE3_Y06,
  SFIELD_SET_DMVA_IMD_ZONE3_Y07,
  SFIELD_SET_DMVA_IMD_ZONE3_Y08,
  SFIELD_SET_DMVA_IMD_ZONE3_Y09,
  SFIELD_SET_DMVA_IMD_ZONE3_Y10,
  SFIELD_SET_DMVA_IMD_ZONE3_Y11,
  SFIELD_SET_DMVA_IMD_ZONE3_Y12,
  SFIELD_SET_DMVA_IMD_ZONE3_Y13,
  SFIELD_SET_DMVA_IMD_ZONE3_Y14,
  SFIELD_SET_DMVA_IMD_ZONE3_Y15,
  SFIELD_SET_DMVA_IMD_ZONE3_Y16,

  SFIELD_SET_DMVA_IMD_ZONE4_X01,
  SFIELD_SET_DMVA_IMD_ZONE4_X02,
  SFIELD_SET_DMVA_IMD_ZONE4_X03,
  SFIELD_SET_DMVA_IMD_ZONE4_X04,
  SFIELD_SET_DMVA_IMD_ZONE4_X05,
  SFIELD_SET_DMVA_IMD_ZONE4_X06,
  SFIELD_SET_DMVA_IMD_ZONE4_X07,
  SFIELD_SET_DMVA_IMD_ZONE4_X08,
  SFIELD_SET_DMVA_IMD_ZONE4_X09,
  SFIELD_SET_DMVA_IMD_ZONE4_X10,
  SFIELD_SET_DMVA_IMD_ZONE4_X11,
  SFIELD_SET_DMVA_IMD_ZONE4_X12,
  SFIELD_SET_DMVA_IMD_ZONE4_X13,
  SFIELD_SET_DMVA_IMD_ZONE4_X14,
  SFIELD_SET_DMVA_IMD_ZONE4_X15,
  SFIELD_SET_DMVA_IMD_ZONE4_X16,

  SFIELD_SET_DMVA_IMD_ZONE4_Y01,
  SFIELD_SET_DMVA_IMD_ZONE4_Y02,
  SFIELD_SET_DMVA_IMD_ZONE4_Y03,
  SFIELD_SET_DMVA_IMD_ZONE4_Y04,
  SFIELD_SET_DMVA_IMD_ZONE4_Y05,
  SFIELD_SET_DMVA_IMD_ZONE4_Y06,
  SFIELD_SET_DMVA_IMD_ZONE4_Y07,
  SFIELD_SET_DMVA_IMD_ZONE4_Y08,
  SFIELD_SET_DMVA_IMD_ZONE4_Y09,
  SFIELD_SET_DMVA_IMD_ZONE4_Y10,
  SFIELD_SET_DMVA_IMD_ZONE4_Y11,
  SFIELD_SET_DMVA_IMD_ZONE4_Y12,
  SFIELD_SET_DMVA_IMD_ZONE4_Y13,
  SFIELD_SET_DMVA_IMD_ZONE4_Y14,
  SFIELD_SET_DMVA_IMD_ZONE4_Y15,
  SFIELD_SET_DMVA_IMD_ZONE4_Y16,

  SFIELD_SET_DMVA_IMD_ZONE1_LABEL,
  SFIELD_SET_DMVA_IMD_ZONE2_LABEL,
  SFIELD_SET_DMVA_IMD_ZONE3_LABEL,
  SFIELD_SET_DMVA_IMD_ZONE4_LABEL,

  SFIELD_SET_DMVA_IMD_SAVE,
  SFIELD_SET_DMVA_IMD_LOAD,

  // DMVA Scheduler
  SFIELD_SET_DMVA_SCH_ENABLE,
  SFIELD_SET_DMVA_SCH_RULETYPE,
  SFIELD_SET_DMVA_SCH_LOADSETTING,
  SFIELD_SET_DMVA_SCH_RULELABEL,
  SFIELD_SET_DMVA_SCH_STARTDAY,
  SFIELD_SET_DMVA_SCH_STARTTIME,
  SFIELD_SET_DMVA_SCH_ENDDAY,
  SFIELD_SET_DMVA_SCH_ENDTIME,
  SFIELD_SET_DMVA_SCH_START,
  SFIELD_SET_DMVA_SCH_DELRULE,
  SFIELD_SET_DMVA_ENC_ROI_ENABLE,

} SYSTEM_CONTROL;

int ControlSystemData(unsigned int field, void *data, unsigned int len); ///<  Protype definition.
/** @} */
#endif   /* __SYS_CONTROL_H__ */
/**
* @page SYSCTRL_HOW How to use system command API?

* 1. Add new command to list if needed.\n
* 2. Now you can use any system command functions as you want.\n
* @section SYSCTRL_HOW_EX Example
* @code
#include <sysctrl.h>
int main()
{
	int value = 0;
	if(ControlSystemData( // system command here, &value, sizeof(value)) < 0){
		return -1;
	}
	return 0;
}
* @endcode
*/
